CREATE DATABASE PASSBOOKMANAGEMENT
GO

USE PASSBOOKMANAGEMENT
GO

CREATE TABLE PASSBOOK
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	DisplayName NVARCHAR(200),
	DateCreate DATE 
)
GO

CREATE TABLE CUSTOMER
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdPassbook INT NOT NULL,
	DisplayName NVARCHAR(100),
	FullName NVARCHAR(100),
	CMND NVARCHAR(20),
	CustomerAddress NVARCHAR(MAX),
	DateDeposit DATE,
	PhoneNumber NVARCHAR(20),
	CustomerMoney INT,
	
	FOREIGN KEY (IdPassbook) REFERENCES PASSBOOK(Id),
)
GO

CREATE TABLE PAYMENT
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	DatePayment DATE,
	IdPassbook INT NOT NULL,
	IdCustomer INT NOT NULL,

	FOREIGN KEY (IdPassbook) REFERENCES PASSBOOK(Id),
	FOREIGN KEY (IdCustomer) REFERENCES CUSTOMER(Id),
)
GO

CREATE TABLE RECEIPTS
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	DateReceipts DATE,
	IdPassbook INT NOT NULL,
	IdCustomer INT NOT NULL,

	FOREIGN KEY (IdPassbook) REFERENCES PASSBOOK(Id),
	FOREIGN KEY (IdCustomer) REFERENCES CUSTOMER(Id),
)
GO

CREATE TABLE USERROLE
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	DisplayName NVARCHAR(100),
)
GO

INSERT INTO USERROLE(DisplayName) VALUES (N'ADMIN')
GO
INSERT INTO USERROLE(DisplayName) VALUES (N'STAFF')
GO

CREATE TABLE USERINFO
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	IdRole INT NOT NULL,
	Username NVARCHAR(200),
	Userpassword NVARCHAR(MAX),

	FOREIGN KEY (IdRole) REFERENCES USERROLE(Id),
)
GO
INSERT INTO USERINFO(Id,Username,Userpassword,IdRole) VALUES (N'admin',N'db69fc039dcbd2962cb4d28f5891aae1',1)
GO
INSERT INTO USERINFO(Id,Username,Userpassword,IdRole) VALUES (N'staff',N'978aae9bb6bee8fb75de3e4830a1be46',2)
GO