//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.PAYMENTs = new HashSet<PAYMENT>();
            this.RECEIPTS = new HashSet<RECEIPT>();
        }
    
        public int Id { get; set; }
        public int IdPassbook { get; set; }
        public string DisplayName { get; set; }
        public string FullName { get; set; }
        public string CMND { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<System.DateTime> DateDeposit { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> CustomerMoney { get; set; }
    
        public virtual PASSBOOK PASSBOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT> PAYMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT> RECEIPTS { get; set; }
    }
}
